project_id = "ykoseamefoabptuijsza"

[functions.gemini-proxy]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payment-callback]
verify_jwt = false

[functions.check-payment]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
